export const treeSitterGrammars = {
  python: {
    id: "python",
    label: "Python",
    package: "tree-sitter-python",
    version: "0.25.0",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-python",
    wasmSizeBytes: 456723,
  },
  java: {
    id: "java",
    label: "Java",
    package: "tree-sitter-java",
    version: "0.23.5",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-java",
    wasmSizeBytes: 414641,
  },
  c: {
    id: "c",
    label: "C",
    package: "tree-sitter-c",
    version: "0.24.1",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-c",
    wasmSizeBytes: 625918,
  },
  cpp: {
    id: "cpp",
    label: "C++",
    package: "tree-sitter-cpp",
    version: "0.23.4",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-cpp",
    wasmSizeBytes: 3434931,
  },
  csharp: {
    id: "csharp",
    label: "C#",
    package: "tree-sitter-c-sharp",
    version: "0.23.5",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-c-sharp",
    wasmSizeBytes: 5350581,
  },
  go: {
    id: "go",
    label: "Go",
    package: "tree-sitter-go",
    version: "0.25.0",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-go",
    wasmSizeBytes: 217182,
  },
  php: {
    id: "php",
    label: "PHP",
    package: "tree-sitter-php",
    version: "0.24.2",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-php",
    wasmSizeBytes: 1058041,
  },
  rust: {
    id: "rust",
    label: "Rust",
    package: "tree-sitter-rust",
    version: "0.24.0",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-rust",
    wasmSizeBytes: 1102547,
  },
  ruby: {
    id: "ruby",
    label: "Ruby",
    package: "tree-sitter-ruby",
    version: "0.23.1",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-ruby",
    wasmSizeBytes: 2106352,
  },
  shell: {
    id: "shell",
    label: "Shell",
    package: "tree-sitter-bash",
    version: "0.25.1",
    license: "MIT",
    upstream: "https://github.com/tree-sitter/tree-sitter-bash",
    wasmSizeBytes: 1358587,
  },
  dockerfile: {
    id: "dockerfile",
    label: "Dockerfile",
    package: "tree-sitter-containerfile",
    version: "0.8.0",
    license: "MIT",
    upstream: "https://github.com/wharflab/tree-sitter-containerfile",
    wasmSizeBytes: 64074,
  },
} as const;

export type TreeSitterGrammarId = keyof typeof treeSitterGrammars;
